spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mybatisplus_db
    username: root
    password: lzy
  main:
    banner-mode: off
mybatis-plus:
  global-config:
    banner: off
    db-config:
      id-type: assign_id
      table-prefix: tbl_
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
